codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1

coverage:
  precision: 1
  round: down
  range: 70...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project: true
    patch: false
    changes: false

comment: false
#comment:
#  layout: "header, diff"
#  behavior: default  # update if exists else create new
