coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project: false
    patch: true
    changes: false

comment: false
#comment:
#  layout: "header, diff"
#  behavior: default  # update if exists else create new
