---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true  # cyclomatic complexity checks
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- src/urh/dev/gr/scripts/
- src/urh/cythonext/path_creator.cpp
- src/urh/cythonext/signalFunctions.cpp
- src/urh/cythonext/util.cpp
- src/urh/dev/native/lib/hackrf.cpp
- src/urh/ui/ui_*
- src/urh/ui/*_rc.py
