trigger:
- master

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -r data/requirements.txt
      sudo apt-get install libhackrf-dev librtlsdr-dev xvfb
      pip install pytest!=4.1 pytest-xdist pytest-xvfb pytest-cov
    displayName: 'Install dependencies'

  - script: python src/urh/cythonext/build.py
    displayName: "Build extensions"

  - script: |
      touch tests/show_gui
      pytest -s --boxed --junitxml=junit/test-results.xml --cov=src/urh --cov-report=xml --cov-report=html --cov-config tests/.coveragerc tests
    displayName: 'pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35-64:
        python.version: '3.5'
        python.arch: 'x64'
      Python35-32:
        python.version: '3.5'
        python.arch: 'x86'
      Python36-64:
        python.version: '3.6'
        python.arch: 'x64'
      Python36-32:
        python.version: '3.6'
        python.arch: 'x86'
      Python37-64:
        python.version: '3.7'
        python.arch: 'x64'
      Python37-32:
        python.version: '3.7'
        python.arch: 'x86'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.arch)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r data/requirements.txt
      pip install pytest pytest-faulthandler
    displayName: 'Install dependencies'

  - script: python setup.py build_ext --inplace
    displayName: "Build extensions"

  - script: pytest --junitxml=junit/test-results.xml -s -v tests
    displayName: 'pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

- job: 'OSX'
  pool:
    vmImage: 'macOS-10.13'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r data/requirements.txt
      pip install pytest pytest-faulthandler
      brew install hackrf librtlsdr
    displayName: 'Install dependencies'

  - script: python setup.py build_ext --inplace
    displayName: "Build extensions"

  - script: pytest --junitxml=junit/test-results.xml -s -v tests
    displayName: 'pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
