#
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCosta(object):
    def setupUi(self, DialogCosta):
        DialogCosta.setObjectName("DialogCosta")
        DialogCosta.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogCosta)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=DialogCosta)
        self.label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLoopBandwidth = QtWidgets.QLabel(parent=DialogCosta)
        self.labelLoopBandwidth.setObjectName("labelLoopBandwidth")
        self.horizontalLayout.addWidget(self.labelLoopBandwidth)
        self.doubleSpinBoxLoopBandwidth = QtWidgets.QDoubleSpinBox(parent=DialogCosta)
        self.doubleSpinBoxLoopBandwidth.setDecimals(4)
        self.doubleSpinBoxLoopBandwidth.setObjectName("doubleSpinBoxLoopBandwidth")
        self.horizontalLayout.addWidget(self.doubleSpinBoxLoopBandwidth)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogCosta)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(DialogCosta)
        self.buttonBox.accepted.connect(DialogCosta.accept)  # type: ignore
        self.buttonBox.rejected.connect(DialogCosta.reject)  # type: ignore

    def retranslateUi(self, DialogCosta):
        _translate = QtCore.QCoreApplication.translate
        DialogCosta.setWindowTitle(_translate("DialogCosta", "Configure Costas Loop"))
        self.label.setText(
            _translate(
                "DialogCosta",
                "URH uses a Costas loop for PSK demodulation. Configure the loop bandwidth below.",
            )
        )
        self.labelLoopBandwidth.setText(_translate("DialogCosta", "Loop Bandwidth:"))
