# -*- coding: utf-8 -*-

#
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChecksumOptions(object):
    def setupUi(self, ChecksumOptions):
        ChecksumOptions.setObjectName("ChecksumOptions")
        ChecksumOptions.resize(478, 397)
        self.gridLayout = QtWidgets.QGridLayout(ChecksumOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(ChecksumOptions)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 107, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.lineEditCRCPolynomial = QtWidgets.QLineEdit(ChecksumOptions)
        self.lineEditCRCPolynomial.setObjectName("lineEditCRCPolynomial")
        self.gridLayout.addWidget(self.lineEditCRCPolynomial, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(ChecksumOptions)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(ChecksumOptions)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ChecksumOptions)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.comboBoxCRCFunction = QtWidgets.QComboBox(ChecksumOptions)
        self.comboBoxCRCFunction.setObjectName("comboBoxCRCFunction")
        self.comboBoxCRCFunction.addItem("")
        self.comboBoxCRCFunction.addItem("")
        self.gridLayout.addWidget(self.comboBoxCRCFunction, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ChecksumOptions)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableViewDataRanges = QtWidgets.QTableView(self.groupBox)
        self.tableViewDataRanges.setObjectName("tableViewDataRanges")
        self.tableViewDataRanges.horizontalHeader().setHighlightSections(False)
        self.tableViewDataRanges.verticalHeader().setCascadingSectionResizes(False)
        self.tableViewDataRanges.verticalHeader().setHighlightSections(False)
        self.horizontalLayout.addWidget(self.tableViewDataRanges)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAddRange = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnAddRange.setIcon(icon)
        self.btnAddRange.setObjectName("btnAddRange")
        self.verticalLayout.addWidget(self.btnAddRange)
        self.btnRemoveRange = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnRemoveRange.setIcon(icon)
        self.btnRemoveRange.setObjectName("btnRemoveRange")
        self.verticalLayout.addWidget(self.btnRemoveRange)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 2)
        self.lineEditFinalXOR = QtWidgets.QLineEdit(ChecksumOptions)
        self.lineEditFinalXOR.setObjectName("lineEditFinalXOR")
        self.gridLayout.addWidget(self.lineEditFinalXOR, 4, 1, 1, 1)
        self.lineEditStartValue = QtWidgets.QLineEdit(ChecksumOptions)
        self.lineEditStartValue.setObjectName("lineEditStartValue")
        self.gridLayout.addWidget(self.lineEditStartValue, 3, 1, 1, 1)

        self.retranslateUi(ChecksumOptions)
        QtCore.QMetaObject.connectSlotsByName(ChecksumOptions)

    def retranslateUi(self, ChecksumOptions):
        _translate = QtCore.QCoreApplication.translate
        ChecksumOptions.setWindowTitle(_translate("ChecksumOptions", "Configure CRC"))
        self.label_3.setText(_translate("ChecksumOptions", "CRC type:"))
        self.label.setText(_translate("ChecksumOptions", "Start value (hex):"))
        self.label_5.setText(_translate("ChecksumOptions", "CRC polynomial (hex):"))
        self.label_2.setText(_translate("ChecksumOptions", "Final XOR (hex):"))
        self.comboBoxCRCFunction.setItemText(0, _translate("ChecksumOptions", "WSP CRC 8"))
        self.comboBoxCRCFunction.setItemText(1, _translate("ChecksumOptions", "WSP CRC 4"))
        self.groupBox.setTitle(_translate("ChecksumOptions", "Configure data ranges for CRC"))
        self.btnAddRange.setText(_translate("ChecksumOptions", "..."))
        self.btnRemoveRange.setText(_translate("ChecksumOptions", "..."))

