

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FuzzingDialog(object):
    def setupUi(self, FuzzingDialog):
        FuzzingDialog.setObjectName("FuzzingDialog")
        FuzzingDialog.resize(825, 666)
        self.gridLayout_5 = QtWidgets.QGridLayout(FuzzingDialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lFuzzingStart = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzingStart.sizePolicy().hasHeightForWidth())
        self.lFuzzingStart.setSizePolicy(sizePolicy)
        self.lFuzzingStart.setObjectName("lFuzzingStart")
        self.gridLayout_5.addWidget(self.lFuzzingStart, 3, 0, 1, 1)
        self.spinBoxFuzzingStart = QtWidgets.QSpinBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFuzzingStart.sizePolicy().hasHeightForWidth())
        self.spinBoxFuzzingStart.setSizePolicy(sizePolicy)
        self.spinBoxFuzzingStart.setMinimum(1)
        self.spinBoxFuzzingStart.setMaximum(999999999)
        self.spinBoxFuzzingStart.setObjectName("spinBoxFuzzingStart")
        self.gridLayout_5.addWidget(self.spinBoxFuzzingStart, 3, 1, 1, 1)
        self.lFuzzingLabel = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzingLabel.sizePolicy().hasHeightForWidth())
        self.lFuzzingLabel.setSizePolicy(sizePolicy)
        self.lFuzzingLabel.setObjectName("lFuzzingLabel")
        self.gridLayout_5.addWidget(self.lFuzzingLabel, 0, 0, 1, 1)
        self.spinBoxFuzzMessage = QtWidgets.QSpinBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFuzzMessage.sizePolicy().hasHeightForWidth())
        self.spinBoxFuzzMessage.setSizePolicy(sizePolicy)
        self.spinBoxFuzzMessage.setMaximum(999999999)
        self.spinBoxFuzzMessage.setObjectName("spinBoxFuzzMessage")
        self.gridLayout_5.addWidget(self.spinBoxFuzzMessage, 2, 1, 1, 1)
        self.lSourceBlock = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lSourceBlock.sizePolicy().hasHeightForWidth())
        self.lSourceBlock.setSizePolicy(sizePolicy)
        self.lSourceBlock.setObjectName("lSourceBlock")
        self.gridLayout_5.addWidget(self.lSourceBlock, 1, 0, 1, 1)
        self.lFuzzingReferenceBlock = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzingReferenceBlock.sizePolicy().hasHeightForWidth())
        self.lFuzzingReferenceBlock.setSizePolicy(sizePolicy)
        self.lFuzzingReferenceBlock.setObjectName("lFuzzingReferenceBlock")
        self.gridLayout_5.addWidget(self.lFuzzingReferenceBlock, 2, 0, 1, 1)
        self.lFuzzingEnd = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzingEnd.sizePolicy().hasHeightForWidth())
        self.lFuzzingEnd.setSizePolicy(sizePolicy)
        self.lFuzzingEnd.setObjectName("lFuzzingEnd")
        self.gridLayout_5.addWidget(self.lFuzzingEnd, 4, 0, 1, 1)
        self.comboBoxFuzzingLabel = QtWidgets.QComboBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFuzzingLabel.sizePolicy().hasHeightForWidth())
        self.comboBoxFuzzingLabel.setSizePolicy(sizePolicy)
        self.comboBoxFuzzingLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxFuzzingLabel.setEditable(True)
        self.comboBoxFuzzingLabel.setObjectName("comboBoxFuzzingLabel")
        self.gridLayout_5.addWidget(self.comboBoxFuzzingLabel, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lFuzzedValues = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzedValues.sizePolicy().hasHeightForWidth())
        self.lFuzzedValues.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lFuzzedValues.setFont(font)
        self.lFuzzedValues.setAlignment(QtCore.Qt.AlignCenter)
        self.lFuzzedValues.setObjectName("lFuzzedValues")
        self.verticalLayout.addWidget(self.lFuzzedValues)
        self.chkBRemoveDuplicates = QtWidgets.QCheckBox(FuzzingDialog)
        self.chkBRemoveDuplicates.setObjectName("chkBRemoveDuplicates")
        self.verticalLayout.addWidget(self.chkBRemoveDuplicates)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnDelRow = QtWidgets.QToolButton(FuzzingDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelRow.setIcon(icon)
        self.btnDelRow.setObjectName("btnDelRow")
        self.gridLayout_4.addWidget(self.btnDelRow, 1, 1, 1, 1)
        self.tblFuzzingValues = FuzzingTableView(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFuzzingValues.sizePolicy().hasHeightForWidth())
        self.tblFuzzingValues.setSizePolicy(sizePolicy)
        self.tblFuzzingValues.setAlternatingRowColors(True)
        self.tblFuzzingValues.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblFuzzingValues.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblFuzzingValues.setShowGrid(False)
        self.tblFuzzingValues.setObjectName("tblFuzzingValues")
        self.tblFuzzingValues.horizontalHeader().setHighlightSections(False)
        self.tblFuzzingValues.verticalHeader().setHighlightSections(False)
        self.gridLayout_4.addWidget(self.tblFuzzingValues, 0, 0, 4, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 3, 1, 1, 1)
        self.btnAddRow = QtWidgets.QToolButton(FuzzingDialog)
        self.btnAddRow.setIcon(icon)
        self.btnAddRow.setObjectName("btnAddRow")
        self.gridLayout_4.addWidget(self.btnAddRow, 0, 1, 1, 1)
        self.btnRepeatValues = QtWidgets.QToolButton(FuzzingDialog)
        self.btnRepeatValues.setIcon(icon)
        self.btnRepeatValues.setObjectName("btnRepeatValues")
        self.gridLayout_4.addWidget(self.btnRepeatValues, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout, 5, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBoxAddRange = QtWidgets.QGroupBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAddRange.sizePolicy().hasHeightForWidth())
        self.groupBoxAddRange.setSizePolicy(sizePolicy)
        self.groupBoxAddRange.setObjectName("groupBoxAddRange")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxAddRange)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lStart = QtWidgets.QLabel(self.groupBoxAddRange)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lStart.sizePolicy().hasHeightForWidth())
        self.lStart.setSizePolicy(sizePolicy)
        self.lStart.setObjectName("lStart")
        self.gridLayout_2.addWidget(self.lStart, 0, 0, 1, 1)
        self.sBAddRangeStart = QtWidgets.QSpinBox(self.groupBoxAddRange)
        self.sBAddRangeStart.setObjectName("sBAddRangeStart")
        self.gridLayout_2.addWidget(self.sBAddRangeStart, 0, 1, 1, 1)
        self.lEnd = QtWidgets.QLabel(self.groupBoxAddRange)
        self.lEnd.setObjectName("lEnd")
        self.gridLayout_2.addWidget(self.lEnd, 1, 0, 1, 1)
        self.sBAddRangeEnd = QtWidgets.QSpinBox(self.groupBoxAddRange)
        self.sBAddRangeEnd.setObjectName("sBAddRangeEnd")
        self.gridLayout_2.addWidget(self.sBAddRangeEnd, 1, 1, 1, 1)
        self.lStep = QtWidgets.QLabel(self.groupBoxAddRange)
        self.lStep.setObjectName("lStep")
        self.gridLayout_2.addWidget(self.lStep, 2, 0, 1, 1)
        self.sBAddRangeStep = QtWidgets.QSpinBox(self.groupBoxAddRange)
        self.sBAddRangeStep.setMinimum(1)
        self.sBAddRangeStep.setObjectName("sBAddRangeStep")
        self.gridLayout_2.addWidget(self.sBAddRangeStep, 2, 1, 1, 1)
        self.btnAddRange = QtWidgets.QPushButton(self.groupBoxAddRange)
        self.btnAddRange.setObjectName("btnAddRange")
        self.gridLayout_2.addWidget(self.btnAddRange, 3, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.groupBoxAddRange)
        self.groupBox = QtWidgets.QGroupBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxLowerBound = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxLowerBound.setChecked(True)
        self.checkBoxLowerBound.setObjectName("checkBoxLowerBound")
        self.gridLayout.addWidget(self.checkBoxLowerBound, 0, 0, 1, 1)
        self.spinBoxLowerBound = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxLowerBound.setObjectName("spinBoxLowerBound")
        self.gridLayout.addWidget(self.spinBoxLowerBound, 0, 1, 1, 1)
        self.checkBoxUpperBound = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxUpperBound.setChecked(True)
        self.checkBoxUpperBound.setObjectName("checkBoxUpperBound")
        self.gridLayout.addWidget(self.checkBoxUpperBound, 1, 0, 1, 1)
        self.spinBoxUpperBound = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxUpperBound.setObjectName("spinBoxUpperBound")
        self.gridLayout.addWidget(self.spinBoxUpperBound, 1, 1, 1, 1)
        self.lNumberBoundaries = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lNumberBoundaries.sizePolicy().hasHeightForWidth())
        self.lNumberBoundaries.setSizePolicy(sizePolicy)
        self.lNumberBoundaries.setObjectName("lNumberBoundaries")
        self.gridLayout.addWidget(self.lNumberBoundaries, 2, 0, 1, 1)
        self.spinBoxBoundaryNumber = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxBoundaryNumber.setMinimum(1)
        self.spinBoxBoundaryNumber.setObjectName("spinBoxBoundaryNumber")
        self.gridLayout.addWidget(self.spinBoxBoundaryNumber, 2, 1, 1, 1)
        self.btnAddBoundaries = QtWidgets.QPushButton(self.groupBox)
        self.btnAddBoundaries.setObjectName("btnAddBoundaries")
        self.gridLayout.addWidget(self.btnAddBoundaries, 3, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBoxxRandom = QtWidgets.QGroupBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxxRandom.sizePolicy().hasHeightForWidth())
        self.groupBoxxRandom.setSizePolicy(sizePolicy)
        self.groupBoxxRandom.setObjectName("groupBoxxRandom")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxxRandom)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lNumRandom = QtWidgets.QLabel(self.groupBoxxRandom)
        self.lNumRandom.setObjectName("lNumRandom")
        self.gridLayout_3.addWidget(self.lNumRandom, 0, 0, 1, 1)
        self.spinBoxNumberRandom = QtWidgets.QSpinBox(self.groupBoxxRandom)
        self.spinBoxNumberRandom.setMinimum(1)
        self.spinBoxNumberRandom.setMaximum(999999999)
        self.spinBoxNumberRandom.setObjectName("spinBoxNumberRandom")
        self.gridLayout_3.addWidget(self.spinBoxNumberRandom, 0, 1, 1, 1)
        self.lRandomMin = QtWidgets.QLabel(self.groupBoxxRandom)
        self.lRandomMin.setObjectName("lRandomMin")
        self.gridLayout_3.addWidget(self.lRandomMin, 1, 0, 1, 1)
        self.spinBoxRandomMinimum = QtWidgets.QSpinBox(self.groupBoxxRandom)
        self.spinBoxRandomMinimum.setObjectName("spinBoxRandomMinimum")
        self.gridLayout_3.addWidget(self.spinBoxRandomMinimum, 1, 1, 1, 1)
        self.lRandomMax = QtWidgets.QLabel(self.groupBoxxRandom)
        self.lRandomMax.setObjectName("lRandomMax")
        self.gridLayout_3.addWidget(self.lRandomMax, 2, 0, 1, 1)
        self.spinBoxRandomMaximum = QtWidgets.QSpinBox(self.groupBoxxRandom)
        self.spinBoxRandomMaximum.setObjectName("spinBoxRandomMaximum")
        self.gridLayout_3.addWidget(self.spinBoxRandomMaximum, 2, 1, 1, 1)
        self.btnAddRandom = QtWidgets.QPushButton(self.groupBoxxRandom)
        self.btnAddRandom.setObjectName("btnAddRandom")
        self.gridLayout_3.addWidget(self.btnAddRandom, 3, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.groupBoxxRandom)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 6, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lPreBits = QtWidgets.QLabel(FuzzingDialog)
        self.lPreBits.setObjectName("lPreBits")
        self.horizontalLayout_2.addWidget(self.lPreBits)
        self.lFuzzedBits = QtWidgets.QLabel(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFuzzedBits.sizePolicy().hasHeightForWidth())
        self.lFuzzedBits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lFuzzedBits.setFont(font)
        self.lFuzzedBits.setAlignment(QtCore.Qt.AlignCenter)
        self.lFuzzedBits.setObjectName("lFuzzedBits")
        self.horizontalLayout_2.addWidget(self.lFuzzedBits)
        self.lPostBits = QtWidgets.QLabel(FuzzingDialog)
        self.lPostBits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPostBits.setObjectName("lPostBits")
        self.horizontalLayout_2.addWidget(self.lPostBits)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.spinBoxFuzzingEnd = QtWidgets.QSpinBox(FuzzingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFuzzingEnd.sizePolicy().hasHeightForWidth())
        self.spinBoxFuzzingEnd.setSizePolicy(sizePolicy)
        self.spinBoxFuzzingEnd.setMinimum(1)
        self.spinBoxFuzzingEnd.setMaximum(999999999)
        self.spinBoxFuzzingEnd.setObjectName("spinBoxFuzzingEnd")
        self.gridLayout_5.addWidget(self.spinBoxFuzzingEnd, 4, 1, 1, 1)

        self.retranslateUi(FuzzingDialog)

    def retranslateUi(self, FuzzingDialog):
        FuzzingDialog.setWindowTitle(QtWidgets.QApplication.translate("FuzzingDialog", "Fuzzing", None, -1))
        self.lFuzzingStart.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Fuzzing Label Start Index:", None, -1))
        self.lFuzzingLabel.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Fuzzing Label:", None, -1))
        self.lSourceBlock.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Source Message:", None, -1))
        self.lFuzzingReferenceBlock.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Message to fuzz:", None, -1))
        self.lFuzzingEnd.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Fuzzing Label End Index:", None, -1))
        self.lFuzzedValues.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Fuzzed Values", None, -1))
        self.chkBRemoveDuplicates.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Remove Duplicates", None, -1))
        self.btnDelRow.setToolTip(QtWidgets.QApplication.translate("FuzzingDialog", "Remove selected values or last value if nothing is selected.", None, -1))
        self.btnDelRow.setText(QtWidgets.QApplication.translate("FuzzingDialog", "...", None, -1))
        self.btnAddRow.setToolTip(QtWidgets.QApplication.translate("FuzzingDialog", "Add a new value.", None, -1))
        self.btnAddRow.setText(QtWidgets.QApplication.translate("FuzzingDialog", "...", None, -1))
        self.btnRepeatValues.setToolTip(QtWidgets.QApplication.translate("FuzzingDialog", "Repeat selected values or all values if nothing is selected.", None, -1))
        self.btnRepeatValues.setText(QtWidgets.QApplication.translate("FuzzingDialog", "...", None, -1))
        self.groupBoxAddRange.setTitle(QtWidgets.QApplication.translate("FuzzingDialog", "Add Range", None, -1))
        self.lStart.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Start (Decimal):", None, -1))
        self.lEnd.setText(QtWidgets.QApplication.translate("FuzzingDialog", "End (Decimal):", None, -1))
        self.lStep.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Step (Decimal):", None, -1))
        self.btnAddRange.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Add to Fuzzed Values", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("FuzzingDialog", "Add Boundaries", None, -1))
        self.checkBoxLowerBound.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Lower Bound", None, -1))
        self.checkBoxUpperBound.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Upper Bound", None, -1))
        self.lNumberBoundaries.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Border Values:", None, -1))
        self.btnAddBoundaries.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Add to Fuzzed Values", None, -1))
        self.groupBoxxRandom.setTitle(QtWidgets.QApplication.translate("FuzzingDialog", "Add random values from range", None, -1))
        self.lNumRandom.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Number:", None, -1))
        self.lRandomMin.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Range Minimum:", None, -1))
        self.lRandomMax.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Range Maximum:", None, -1))
        self.btnAddRandom.setText(QtWidgets.QApplication.translate("FuzzingDialog", "Add to Fuzzed Values", None, -1))
        self.lPreBits.setText(QtWidgets.QApplication.translate("FuzzingDialog", "1111", None, -1))
        self.lFuzzedBits.setText(QtWidgets.QApplication.translate("FuzzingDialog", "1010", None, -1))
        self.lPostBits.setText(QtWidgets.QApplication.translate("FuzzingDialog", "010101", None, -1))

from urh.ui.views.FuzzingTableView import FuzzingTableView
