# -*- coding: utf-8 -*-

#
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProtocolLabelDialog(object):
    def setupUi(self, ProtocolLabelDialog):
        ProtocolLabelDialog.setObjectName("ProtocolLabelDialog")
        ProtocolLabelDialog.resize(483, 450)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProtocolLabelDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 11, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 3, 1, 1)
        self.spinBoxLabelStart = QtWidgets.QSpinBox(ProtocolLabelDialog)
        self.spinBoxLabelStart.setMinimum(1)
        self.spinBoxLabelStart.setMaximum(999999999)
        self.spinBoxLabelStart.setObjectName("spinBoxLabelStart")
        self.gridLayout_2.addWidget(self.spinBoxLabelStart, 1, 1, 1, 5)
        self.spinBoxLabelEnd = QtWidgets.QSpinBox(ProtocolLabelDialog)
        self.spinBoxLabelEnd.setMinimum(1)
        self.spinBoxLabelEnd.setMaximum(999999999)
        self.spinBoxLabelEnd.setObjectName("spinBoxLabelEnd")
        self.gridLayout_2.addWidget(self.spinBoxLabelEnd, 2, 1, 1, 5)
        self.comboBoxName = QtWidgets.QComboBox(ProtocolLabelDialog)
        self.comboBoxName.setEditable(True)
        self.comboBoxName.setObjectName("comboBoxName")
        self.gridLayout_2.addWidget(self.comboBoxName, 0, 1, 1, 5)
        self.comboBox_3 = QtWidgets.QComboBox(ProtocolLabelDialog)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 8, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(ProtocolLabelDialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 8, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(ProtocolLabelDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(ProtocolLabelDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 8, 5, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(ProtocolLabelDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 11, 4, 1, 2)
        self.toolButton = QtWidgets.QToolButton(ProtocolLabelDialog)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 11, 6, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(ProtocolLabelDialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 6, 4, 1, 3)
        self.radioButton = QtWidgets.QRadioButton(ProtocolLabelDialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 4, 1, 1, 6)
        self.radioButton_4 = QtWidgets.QRadioButton(ProtocolLabelDialog)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 3, 1, 1, 6)
        self.radioButton_2 = QtWidgets.QRadioButton(ProtocolLabelDialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 5, 1, 1, 6)
        self.radioButton_5 = QtWidgets.QRadioButton(ProtocolLabelDialog)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_2.addWidget(self.radioButton_5, 9, 1, 1, 6)
        self.radioButton_3 = QtWidgets.QRadioButton(ProtocolLabelDialog)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 12, 1, 1, 6)
        self.btnSaveAndClose = QtWidgets.QPushButton(ProtocolLabelDialog)
        self.btnSaveAndClose.setObjectName("btnSaveAndClose")
        self.gridLayout_2.addWidget(self.btnSaveAndClose, 13, 0, 1, 7)

        self.retranslateUi(ProtocolLabelDialog)
        QtCore.QMetaObject.connectSlotsByName(ProtocolLabelDialog)

    def retranslateUi(self, ProtocolLabelDialog):
        _translate = QtCore.QCoreApplication.translate
        ProtocolLabelDialog.setWindowTitle(_translate("ProtocolLabelDialog", "Protocol label"))
        self.label.setText(_translate("ProtocolLabelDialog", "Name:"))
        self.label_6.setText(_translate("ProtocolLabelDialog", "External program:"))
        self.label_5.setText(_translate("ProtocolLabelDialog", "Label:"))
        self.comboBox_3.setItemText(0, _translate("ProtocolLabelDialog", "Add"))
        self.comboBox_3.setItemText(1, _translate("ProtocolLabelDialog", "Subtract"))
        self.checkBox.setText(_translate("ProtocolLabelDialog", "Adjust value:"))
        self.label_3.setText(_translate("ProtocolLabelDialog", "End index:"))
        self.label_2.setText(_translate("ProtocolLabelDialog", "Start index:"))
        self.label_4.setText(_translate("ProtocolLabelDialog", "Value:"))
        self.toolButton.setText(_translate("ProtocolLabelDialog", "..."))
        self.radioButton.setText(_translate("ProtocolLabelDialog", "Get live during simulation"))
        self.radioButton_4.setText(_translate("ProtocolLabelDialog", "Constant value"))
        self.radioButton_2.setText(_translate("ProtocolLabelDialog", "Protocol label"))
        self.radioButton_5.setText(_translate("ProtocolLabelDialog", "External program"))
        self.radioButton_3.setText(_translate("ProtocolLabelDialog", "Random value"))
        self.btnSaveAndClose.setText(_translate("ProtocolLabelDialog", "Save and Close"))

