/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__src__urh__dev__native__lib__limesdr
#define __PYX_HAVE__src__urh__dev__native__lib__limesdr


#ifndef __PYX_HAVE_API__src__urh__dev__native__lib__limesdr

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(bool) IS_TX;

#endif /* !__PYX_HAVE_API__src__urh__dev__native__lib__limesdr */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlimesdr(void);
#else
PyMODINIT_FUNC PyInit_limesdr(void);
#endif

#endif /* !__PYX_HAVE__src__urh__dev__native__lib__limesdr */
