#ifdef RTLSDR_BANDWIDTH_SUPPORT
#define RTLSDR_BANDWIDTH_SUPPORT 1
#else
#define RTLSDR_BANDWIDTH_SUPPORT 0
#endif

#ifdef HACKRF_MULTI_DEVICE_SUPPORT
#define HACKRF_MULTI_DEVICE_SUPPORT 1
#else
#define HACKRF_MULTI_DEVICE_SUPPORT 0
#endif