#ifdef RTLSDR_BANDWIDTH
#define RTLSDR_HAS_BANDWIDTH 1
#else
#define RTLSDR_HAS_BANDWIDTH 0
#endif

#ifdef HACKRF_MULTI_DEVICE
#define HACKRF_HAS_MULTI_DEVICE 1
#else
#define HACKRF_HAS_MULTI_DEVICE 0
#endif